# Generated by Django 2.2.5 on 2020-01-15 06:21

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField(blank=True)),
                ('beds', models.IntegerField(blank=True, default=0)),
                ('bathrooms', models.IntegerField(blank=True, default=0)),
                ('bath', models.IntegerField(blank=True, default=0)),
                ('price', models.IntegerField(blank=True, default=0)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('checkIn', models.TimeField()),
                ('checkOut', models.TimeField()),
            ],
        ),
    ]
