# Generated by Django 2.2.5 on 2020-01-15 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20200115_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='instant_book',
            new_name='is_instantBook',
        ),
    ]
